name: "Build for Windows"

on:
  push:

jobs:
  build_windows_artifact:
    name: Build Windows artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8.x
      - name: PNPM Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Package
        run: pnpm run package
      - name: Save exe
        uses: actions/upload-artifact@v4
        with:
          name: keyboard-autoflasher.exe
          path: dist/keyboard-autoflasher.exe
      
